version: '3.9'

services:
  backend:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
      target: backend
    image: primea/blockscout-backend:dev
    restart: always
    stop_grace_period: 5m
    container_name: 'backend'
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    env_file:
      - /opt/primea/blockscout/docker-compose/envs/common-blockscout.env
    volumes:
      - ./logs/:/app/logs/
      - ./dets/:/app/dets/

