version: '3.9'

services:
  frontend:
    image: ghcr.io/blockscout/frontend:${FRONTEND_DOCKER_TAG:-latest}
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      - /opt/primea/blockscout/docker-compose/envs/common-frontend.env
    ports:
      - "3000:3000"
    #healthcheck:
      #test: ["CMD", "curl", "-f", "http://127.0.0.1:3000"]
      #interval: 10s
      #timeout: 5s
      #retries: 5
