version: '3.9'

services:
  nft_media_handler:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: nft-media-handler
    image: primea/blockscout-nft-media-handler:dev
    restart: always
    stop_grace_period: 5m
    container_name: 'nft_media_handler'
    command: sh -c "bin/blockscout start"
    env_file:
      -  ./envs/common-nft-media-handler.env
    volumes:
      - ./logs/:/app/logs/
