version: '3.9'

services:
  sig-provider:
    build:
      context: ../../
      dockerfile: ./Dockerfile
    image: primea/blockscout-sig-provider:dev
    platform: linux/amd64
    restart: always
    container_name: 'sig-provider'
